# Generated by Django 3.1.5 on 2021-02-03 17:44

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20210203_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='media/avatars/default.jpeg', upload_to='media/avatars'),
        ),
    ]
