# Generated by Django 3.1.5 on 2021-02-03 17:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0004_auto_20210203_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/default.jpeg', upload_to='avatars'),
        ),
    ]
