# Generated by Django 3.1.5 on 2021-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0005_auto_20210203_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='avatar',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
