# Generated by Django 3.1.5 on 2021-02-07 21:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0006_auto_20210206_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatars/default.jpg', upload_to='avatars'),
        ),
    ]
