# Generated by Django 3.1.5 on 2021-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0007_auto_20210207_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='friends',
            field=models.ManyToManyField(default=None, to='messanger.Consumer', verbose_name='Friends'),
        ),
    ]
