# Generated by Django 3.1.5 on 2021-02-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0008_consumer_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='messanger.Consumer', verbose_name='Friends'),
        ),
    ]
