# Generated by Django 3.1.5 on 2021-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0009_auto_20210207_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, to='messanger.Consumer', verbose_name='Friends'),
        ),
    ]
