# Generated by Django 3.1.5 on 2021-02-08 17:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0011_auto_20210208_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='chats/default.jpg', upload_to='chats'),
        ),
    ]
