# Generated by Django 3.1.5 on 2021-02-09 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0013_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privaters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
