# Generated by Django 3.1.5 on 2021-02-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0017_addtofriendnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtofriendnotification',
            name='agreed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
