# Generated by Django 3.1.5 on 2021-02-25 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messanger', '0018_auto_20210225_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtofriendnotification',
            name='send_by',
        ),
        migrations.AddField(
            model_name='addtofriendnotification',
            name='send_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_from', to='auth.user'),
            preserve_default=False,
        ),
    ]
