# Generated by Django 3.1.5 on 2021-02-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0020_addtofriendnotification_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtofriendnotification',
            name='checked',
        ),
    ]
