# Generated by Django 3.1.5 on 2021-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0021_remove_addtofriendnotification_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
